import inquirer from "inquirer";
import chalk from "chalk";
import ora from "ora";
import { join } from "node:path";
import { writeFileSync } from "node:fs";
import { getAuthClient, fetchProjects } from "../lib/api.js";
import { saveCredentials, config, loadCredentials, EZEO_DIR, ensureDir } from "../lib/config.js";
import { logo } from "../lib/formatter.js";
import { initProjectMemory, getSoul } from "../lib/memory.js";

const lemon = chalk.hex("#F5E642");
const cyan = chalk.hex("#00D4FF");
const lime = chalk.hex("#7CE850");

export async function setupCommand(): Promise<void> {
  console.log();
  console.log(logo());
  console.log();
  console.log(lemon.bold("  Welcome to Ezeo CLI — Setup Wizard"));
  console.log(chalk.gray("  This wizard will configure your CLI in under a minute."));
  console.log();

  // Check if already configured
  const existingCreds = loadCredentials();
  if (existingCreds) {
    const { proceed } = await inquirer.prompt([
      {
        type: "confirm",
        name: "proceed",
        message: `You're already logged in as ${cyan(existingCreds.user_email)}. Re-configure?`,
        default: false,
      },
    ]);
    if (!proceed) {
      console.log();
      console.log(chalk.gray("  Nothing changed. Run `ezeo status` to check your dashboard."));
      console.log();
      return;
    }
  }

  // Step 1: Credentials
  console.log(chalk.gray("  Step 1/3: Login to your Ezeo account"));
  console.log();

  const { email, password } = await inquirer.prompt([
    {
      type: "input",
      name: "email",
      message: "Email:",
      validate: (v: string) => (v.includes("@") ? true : "Enter a valid email"),
    },
    {
      type: "password",
      name: "password",
      message: "Password:",
      mask: "*",
      validate: (v: string) => (v.length > 0 ? true : "Password is required"),
    },
  ]);

  const spinner = ora("Authenticating...").start();

  try {
    const supabase = await getAuthClient();
    const { data, error } = await supabase.auth.signInWithPassword({ email, password });

    if (error || !data.session) {
      spinner.fail("Authentication failed");
      console.log(chalk.red(`  ${error?.message ?? "Invalid credentials"}`));
      console.log(chalk.gray("  Tip: Check your email and password at app.ezeo.ai"));
      process.exit(1);
    }

    saveCredentials({
      access_token: data.session.access_token,
      refresh_token: data.session.refresh_token,
      expires_at: data.session.expires_at ?? 0,
      user_email: email,
    });

    spinner.succeed(`Logged in as ${cyan(email)}`);
  } catch (err) {
    spinner.fail("Login failed");
    console.log(chalk.red(`  ${err instanceof Error ? err.message : String(err)}`));
    process.exit(1);
  }

  // Step 2: Pick default project
  console.log();
  console.log(chalk.gray("  Step 2/3: Choose your default project"));
  console.log();

  const projectSpinner = ora("Loading projects...").start();
  let projects;
  try {
    projects = await fetchProjects();
    projectSpinner.stop();
  } catch (err) {
    projectSpinner.fail("Failed to load projects");
    console.log(chalk.red(`  ${err instanceof Error ? err.message : String(err)}`));
    process.exit(1);
  }

  if (projects.length === 0) {
    console.log(chalk.gray("  No projects found. Create one at app.ezeo.ai first."));
  } else {
    const projectChoices = projects.map((p) => ({
      name: `${p.name} ${chalk.gray(`(${p.domain})`)}`,
      value: p.id,
      short: p.name,
    }));

    const { defaultProjectId } = await inquirer.prompt([
      {
        type: "list",
        name: "defaultProjectId",
        message: "Default project:",
        choices: projectChoices,
      },
    ]);

    const chosen = projects.find((p) => p.id === defaultProjectId)!;
    config.set("defaultProject", chosen.id);
    config.set("defaultProjectName", chosen.name);
    console.log(lime(`  ✓ Default project: ${chalk.white.bold(chosen.name)}`));

    // Initialize memory for all projects
    for (const p of projects) {
      initProjectMemory(p.name, p.domain ?? "");
    }
    getSoul();
  }

  // Step 3: Write ~/.ezeo/.env
  console.log();
  console.log(chalk.gray("  Step 3/3: Saving config to ~/.ezeo/.env"));
  console.log();

  ensureDir();
  const envPath = join(EZEO_DIR, ".env");
  const envContent = [
    "# Ezeo CLI config — auto-generated by `ezeo setup`",
    `# Saved: ${new Date().toISOString()}`,
    "",
    "# Uncomment to override the bundled Supabase URL:",
    "# EZEO_SUPABASE_URL=https://nnzukmaididuhuxsaotn.supabase.co",
    "",
  ].join("\n");

  writeFileSync(envPath, envContent, "utf-8");
  console.log(lime(`  ✓ Config saved to ${chalk.gray(envPath)}`));

  // Done
  console.log();
  console.log(lemon.bold("  You're all set! 🎉"));
  console.log();
  console.log(`  ${chalk.white("Next steps:")}`);
  console.log(`    ${cyan("ezeo status")}          — View your project dashboard`);
  console.log(`    ${cyan("ezeo chat")}             — Ask questions about your SEO data`);
  console.log(`    ${cyan("ezeo report")}           — Generate a full performance report`);
  console.log(`    ${cyan("ezeo geo")}              — Check AI citation visibility`);
  console.log(`    ${cyan("ezeo doctor")}           — Verify connectivity & auth`);
  console.log();
}
